server:
  port: ${PORT:8080}
telegram:
  bot:
    wfwbf:
      name: ${WFWBF_BOT_NAME}
      token: ${WFWBF_BOT_TOKEN}
    wfw-terminal:
      name: ${WFW_TERMINAL_BOT_NAME}
      token: ${WFW_TERMINAL_BOT_TOKEN}
